### ISSUE TITLE
Describe Cardano ADA software wallets (Daedulus, Yoroi) key derivation compatibility

### ISSUE THREAD

**Issue by dougnukem** [nvk/walletsrecovery.org#162]
Cardano Wallets have a history of different wallet master key derivation implementations.
- https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/CIP-0003.md#history

The main Cardano software wallets (Daedalus and Yoroi) appear to implement a key derivation method called [Icarus](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/Icarus.md).

Two hardware wallets implement a different key derivation method (making a BIP39 recovery seed from a software wallet essentially incompatible)
- [Ledger Cardano master key generation](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/Ledger.md)
- [Icarus-Trezor](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/Icarus.md) - Trezor historically has implemented a BIP39 24 word master key that differs from the standard Icarus derivation
  - Trezor fixed in a future firmware - https://github.com/trezor/trezor-firmware/pull/1388
 

I don't know enough about BIP39 key derivation methods to properly document the Cardano software wallet compatibilities, but I think it would be helpful to add to this project as it's an instance of incompatibility of wallet recovery methods.

**Comment by nvk** [comment]
not bitcoin related.
