### ISSUE TITLE
Add Blixt

### ISSUE THREAD

**Issue by Darth-Coin** [nvk/walletsrecovery.org#192]
Blixt is a pure LND aezeed wallet 
m/84/0/0 derivation path
https://github.com/hsjoberg/blixt-wallet
https://blixtwallet.com

As Shinobi said 😂😂 :

[![Blixt-bar-lnd-wrapper.jpg](https://i.postimg.cc/rmbpnkB2/Blixt-bar-lnd-wrapper.jpg)](https://postimg.cc/qhs0q9B1)

I could add a PR if you want, but I don't want to meddle into your nice page.

**Comment by nvk** [comment]
yeah, if you don't mind a PR would be helpful.
